name: application_mapollege
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  google_sign_in: ^7.1.1
  get: ^4.7.3
  dio: ^5.8.0+1
  google_maps_flutter: ^2.12.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.9.1
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  uuid: ^4.5.1
  intl: ^0.20.2
  photo_view: ^0.15.0
  clipboard: ^2.0.2
  flutter_datetime_picker_plus: ^2.2.0
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  flutter_animate_on_scroll: ^0.3.0
  vibration: ^3.1.3
  badges: ^3.1.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  flutter_dotenv: ^6.0.0
  flutter_polyline_points: ^3.1.0
  url_launcher: ^6.3.2
  flutter_sliding_up_panel: ^2.1.1
  pull_to_refresh: ^2.0.0
  sliding_up_panel2: ^3.3.0+1
  mobile_scanner: ^7.1.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/images/"
    - "assets/icons/"
    - ".env"
